-- Скрипт для проведения исследования

-- процедура инициализации источника
DELETE T_SOURCE;
EXEC SP_INIT_SOURCE 500;

-- Создание ключей для ключа/значение
DELETE FROM T_DATA_KEY;
INSERT INTO T_DATA_KEY(ID, NAME) VALUES(1, N'SUM');
INSERT INTO T_DATA_KEY(ID, NAME) VALUES(2, N'SUM1');
INSERT INTO T_DATA_KEY(ID, NAME) VALUES(3, N'SUM2');
INSERT INTO T_DATA_KEY(ID, NAME) VALUES(4, N'SUM3');
INSERT INTO T_DATA_KEY(ID, NAME) VALUES(5, N'SUM4');
INSERT INTO T_DATA_KEY(ID, NAME) VALUES(6, N'FLAG');
INSERT INTO T_DATA_KEY(ID, NAME) VALUES(7, N'FLAG1');
INSERT INTO T_DATA_KEY(ID, NAME) VALUES(8, N'FLAG2');
INSERT INTO T_DATA_KEY(ID, NAME) VALUES(9, N'STR');
INSERT INTO T_DATA_KEY(ID, NAME) VALUES(10, N'STR1');
INSERT INTO T_DATA_KEY(ID, NAME) VALUES(11, N'STR2');	

DECLARE @ROWCOUNT INT; -- Количество строк в операторе
DECLARE @MAXCOUNT INT; -- Максимальное количество строк в оператор
DECLARE @START DATETIME2; -- Время начала выполнения
DECLARE @ATTEMPT INT; -- Номер повторения
DECLARE @MAXATTEMPT INT; -- Количество повторений
DECLARE @ROWDELTA INT;

SET @MAXATTEMPT=2;
SET @ROWDELTA=50000;

-- максимальное кол-во данных
SELECT @MAXCOUNT=COUNT(*) FROM [T_SOURCE];

DELETE FROM T_TEST_RESULT;

SET @ATTEMPT=1;
WHILE (@ATTEMPT<=@MAXATTEMPT)
BEGIN
	-- STANDART
	SET @ROWCOUNT=0;
	SET @ROWCOUNT=@ROWDELTA;
	WHILE (@ROWCOUNT<=@MAXCOUNT)
	BEGIN
		SET @START=GETDATE();
		-- Испытание
		INSERT INTO [T_STANDART]([TYPE_ID], [SUM], [SUM1], [SUM2], [SUM3], [SUM4], [FLAG], [FLAG1], [FLAG2], [STR], [STR1], [STR2])
			SELECT TOP (@ROWCOUNT)
					[TYPE_ID], [SUM], [SUM1], [SUM2], [SUM3], [SUM4], [FLAG], [FLAG1], [FLAG2], [STR], [STR1], [STR2]
				FROM T_SOURCE
		--
		INSERT [T_TEST_RESULT] ([TABLE_NAME], [OPERATION_NAME], [COUNT], [ATTEMPT], [NS])
		VALUES(N'T_STANDART','INSERT', @ROWCOUNT, @ATTEMPT, DATEDIFF(mcs, @START, GETDATE()));
		SET @ROWCOUNT=@ROWCOUNT+@ROWDELTA;
	END

	SET @ROWCOUNT=0;
	SET @ROWCOUNT=@ROWDELTA;
	WHILE (@ROWCOUNT<=@MAXCOUNT)
	BEGIN
		SET @START=GETDATE();
		-- Испытание
		INSERT INTO T_RESULT([TYPE_ID], [SUM], [SUM1], [SUM2], [SUM3], [SUM4], [FLAG], [FLAG1], [FLAG2], [STR], [STR1], [STR2])
			SELECT TOP (@ROWCOUNT)
					[TYPE_ID], [SUM], [SUM1], [SUM2], [SUM3], [SUM4], [FLAG], [FLAG1], [FLAG2], [STR], [STR1], [STR2]
				FROM T_STANDART
		--
		INSERT [T_TEST_RESULT] ([TABLE_NAME], [OPERATION_NAME], [COUNT], [ATTEMPT], [NS])
		VALUES(N'T_STANDART','SELECT', @ROWCOUNT, @ATTEMPT, DATEDIFF(mcs, @START, GETDATE()));
		SET @ROWCOUNT=@ROWCOUNT+@ROWDELTA;
	END

	DELETE FROM [T_STANDART];
	DELETE FROM [T_RESULT]

	-- JSON
	SET @ROWCOUNT=0;
	SET @ROWCOUNT=@ROWDELTA;
	WHILE (@ROWCOUNT<=@MAXCOUNT)
	BEGIN
		SET @START=GETDATE();
		-- Испытание
		INSERT INTO [T_JSON]([TYPE_ID], [STRING_DATA])
			SELECT TOP (@ROWCOUNT)
					[TYPE_ID], (SELECT [SUM], [SUM1], [SUM2], [SUM3], [SUM4], [FLAG], [FLAG1], [FLAG2], [STR], [STR1], [STR2] FOR JSON PATH , WITHOUT_ARRAY_WRAPPER) AS [DATE_STRING] 
				FROM T_SOURCE
		--
		INSERT [T_TEST_RESULT] ([TABLE_NAME], [OPERATION_NAME], [COUNT], [ATTEMPT], [NS])
		VALUES(N'T_JSON','INSERT', @ROWCOUNT, @ATTEMPT, DATEDIFF(mcs, @START, GETDATE()));
		SET @ROWCOUNT=@ROWCOUNT+@ROWDELTA;
	END

	--
	SET @ROWCOUNT=0;
	SET @ROWCOUNT=@ROWDELTA;
	WHILE (@ROWCOUNT<=@MAXCOUNT)
	BEGIN
		SET @START=GETDATE();
		-- Испытание
		INSERT INTO T_RESULT([TYPE_ID], [SUM], [SUM1], [SUM2], [SUM3], [SUM4], [FLAG], [FLAG1], [FLAG2], [STR], [STR1], [STR2])
			SELECT TOP (@ROWCOUNT)
					[TYPE_ID], 
					JSON_VALUE([STRING_DATA],N'$.SUM' ) AS [SUM], 
					JSON_VALUE([STRING_DATA],N'$.SUM1') AS [SUM1], 
					JSON_VALUE([STRING_DATA],N'$.SUM2') AS [SUM2], 
					JSON_VALUE([STRING_DATA],N'$.SUM3') AS [SUM3], 
					JSON_VALUE([STRING_DATA],N'$.SUM4') AS [SUM4], 
					JSON_VALUE([STRING_DATA],N'$.FLAG') AS [FLAG], 
					JSON_VALUE([STRING_DATA],N'$.FLAG1') AS [FLAG1], 
					JSON_VALUE([STRING_DATA],N'$.FLAG2') AS [FLAG2], 
					JSON_VALUE([STRING_DATA],N'$.STR') AS [STR], 
					JSON_VALUE([STRING_DATA],N'$.STR1') AS [STR1], 
					JSON_VALUE([STRING_DATA],N'$.STR2') AS [STR2] 
				FROM T_JSON
		--
		INSERT [T_TEST_RESULT] ([TABLE_NAME], [OPERATION_NAME], [COUNT], [ATTEMPT], [NS])
		VALUES(N'T_JSON','SELECT', @ROWCOUNT, @ATTEMPT, DATEDIFF(mcs, @START, GETDATE()));
		SET @ROWCOUNT=@ROWCOUNT+@ROWDELTA;
	END

	DELETE FROM [T_JSON]
	DELETE FROM [T_RESULT]

	-- XML
	SET @ROWCOUNT=0;
	SET @ROWCOUNT=@ROWDELTA;
	WHILE (@ROWCOUNT<=@MAXCOUNT)
	BEGIN
		SET @START=GETDATE();
		-- Испытание
		INSERT INTO [T_XML]([TYPE_ID], [STRING_DATA])
			SELECT TOP (@ROWCOUNT)
					[TYPE_ID], (SELECT [SUM], [SUM1], [SUM2], [SUM3], [SUM4], [FLAG], [FLAG1], [FLAG2], [STR], [STR1], [STR2] FOR XML PATH) AS [DATE_STRING] 
				FROM T_SOURCE
		--
		INSERT [T_TEST_RESULT] ([TABLE_NAME], [OPERATION_NAME], [COUNT], [ATTEMPT], [NS])
		VALUES(N'T_XML','INSERT', @ROWCOUNT, @ATTEMPT, DATEDIFF(mcs, @START, GETDATE()));
		SET @ROWCOUNT=@ROWCOUNT+@ROWDELTA;
	END

	--
	SET @ROWCOUNT=0;
	SET @ROWCOUNT=@ROWDELTA;
	WHILE (@ROWCOUNT<=@MAXCOUNT)
	BEGIN
		SET @START=GETDATE();
		-- Испытание
		INSERT INTO T_RESULT([TYPE_ID], [SUM], [SUM1], [SUM2], [SUM3], [SUM4], [FLAG], [FLAG1], [FLAG2], [STR], [STR1], [STR2])
			SELECT TOP (@ROWCOUNT)
					[TYPE_ID], 
					[STRING_DATA].value('/row[1]/SUM[1]','decimal(18,2)') AS [SUM], 
					[STRING_DATA].value('/row[1]/SUM1[1]','decimal(18,2)') AS [SUM1], 
					[STRING_DATA].value('/row[1]/SUM2[1]','decimal(18,2)') AS [SUM2], 
					[STRING_DATA].value('/row[1]/SUM3[1]','decimal(18,2)') AS [SUM3], 
					[STRING_DATA].value('/row[1]/SUM4[1]','decimal(18,2)') AS [SUM4], 
					[STRING_DATA].value('/row[1]/FLAG[1]','bit') AS [FLAG], 
					[STRING_DATA].value('/row[1]/FLAG1[1]','bit') AS [FLAG1], 
					[STRING_DATA].value('/row[1]/FLAG2[1]','bit') AS [FLAG2], 
					[STRING_DATA].value('/row[1]/STR[1]','nvarchar(5)') AS [STR], 
					[STRING_DATA].value('/row[1]/STR1[1]','nvarchar(30)') AS [STR1], 
					[STRING_DATA].value('/row[1]/STR2[1]','nvarchar(70)') AS [STR2] 
				FROM T_JSON
		--
		INSERT [T_TEST_RESULT] ([TABLE_NAME], [OPERATION_NAME], [COUNT], [ATTEMPT], [NS])
		VALUES(N'T_XML','SELECT', @ROWCOUNT, @ATTEMPT, DATEDIFF(mcs, @START, GETDATE()));
		SET @ROWCOUNT=@ROWCOUNT+@ROWDELTA;
	END

	DELETE FROM [T_XML]
	DELETE FROM [T_RESULT]

	SET @ATTEMPT=@ATTEMPT+1;
END

SELECT 
	[TABLE_NAME], [OPERATION_NAME], [COUNT],
	COUNT(*) AS ATTEMPT_COUNT,
	AVG(CAST([NS] AS FLOAT))/1000
FROM [T_TEST_RESULT]
GROUP BY [TABLE_NAME], [OPERATION_NAME], [COUNT]

