CREATE TABLE [dbo].[T_SOURCE]
(
	[ID] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [TYPE_ID] BIGINT NOT NULL, 
    [S_CREATED_USER] NVARCHAR(255) NOT NULL DEFAULT USER_NAME(), 
    [S_CREATED_TIME] DATETIME2 NOT NULL DEFAULT GETDATE()
)
