CREATE TABLE [dbo].[T_DATA_VALUE]
(
	[ID] BIGINT NOT NULL PRIMARY KEY, 
    [KEY_ID] BIGINT NOT NULL, 
    [VALUE_DECIMAL] DECIMAL(18, 2) NULL, 
    [VALUE_BIT] BIT NULL, 
    [VALUE_STRING] NVARCHAR(70) NULL
)
